# Generated by Django 5.1 on 2024-08-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0015_contactsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='logo',
        ),
    ]
