# Generated by Django 5.1 on 2024-08-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_remove_social_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
